// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	ListTasks(ctx context.Context, organisationID string) ([]Task, error)
	ListUsers(ctx context.Context, organisationID string) ([]User, error)
}

var _ Querier = (*Queries)(nil)
