run:
  timeout: 10m
linters:
  disable-all: false
  enable:
    - misspell
    - gofmt
    - unconvert
    - errcheck
    - errorlint
    - staticcheck
    - ineffassign
    - gosimple
    - deadcode
    - structcheck
    - typecheck
    - varcheck
    - gocyclo
    - gosec
    - nakedret
    - prealloc
    # - wrapcheck

linters-settings:
  cyclop:
    # the maximal code complexity to report
    max-complexity: 10
    # the maximal average package complexity. If it's higher than 0.0 (float) the check is enabled (default 0.0)
    package-average: 0.0
    # should ignore tests (default false)
    skip-tests: false

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec